### ISSUE TITLE
Example of how InterpolatedSql will work if IDbConnection has Transaction?

### ISSUE THREAD

**Issue by AsuraKev** [Drizin/InterpolatedSql#16]

**Comment by AsuraKev** [comment]
Hi there, sorry I have encountered an error saying **BeginExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized**

When my DbConnection goes BeginTransaction(), and it seems not like it :(. Any idea what its complaining?

thanks :)

**Comment by Drizin** [comment]
Please share a small example where the problem can be reproduced.

**Comment by AsuraKev** [comment]
I have somehow resolved the issue. The resolution was to pass in the transaction parameter.. But here is a small example where its reproduced. It seems like we have to pass in transaction if the connection has an active transaction. Please confirm if this is the correct behaviour :) thanks!

![image](https://github.com/Drizin/InterpolatedSql/assets/52765572/53eeeba6-a5ea-409f-8c2b-d4fa6675fb08)

**Comment by Drizin** [comment]
Yep, passing the transaction to the extension methods (preferably using named parameter to avoid calling the wrong overload) seems to be the correct way of using transactions in Dapper.
https://github.com/DapperLib/Dapper/issues/713

**Comment by AsuraKev** [comment]
thanks for the link and the help! :)
