### ISSUE TITLE
Updating DB Keywords

### ISSUE THREAD

**Issue by mcflie1994** [Drizin/InterpolatedSql#2]
Thank you very much for this wonderfully simple library. Are there any plans to implement functions for keywords like UPDATE, SET, INSERT INTO etc? I would love to be able to use this library on more than just a reading level. Am I just missing this or is there a reason it is not provided?

**Comment by Drizin** [comment]
In the new library the aforementioned examples are here: https://github.com/Drizin/InterpolatedSql/blob/main/Builders.md#static-command
And you should use `.SqlBuilder()` instead of `.CommandBuilder()`.

**Comment by Drizin** [comment]
There's a new [InsertUpdateBuilder](https://github.com/Drizin/InterpolatedSql/blob/62b02f22fccf8aa6a4be0bd44ec355ea57ec5e3b/src/InterpolatedSql/SqlBuilders/InsertUpdateBuilder/InsertUpdateBuilder%7BU%2CRB%2CR%7D.cs#L91). Sample usage [here](https://github.com/Drizin/InterpolatedSql/blob/62b02f22fccf8aa6a4be0bd44ec355ea57ec5e3b/src/InterpolatedSql.Dapper.Tests/InsertUpdateTests.cs#L25)
