### ISSUE TITLE
QueryBuilder missing AppendLine( FormattableString )

### ISSUE THREAD

**Issue by terryaney** [Drizin/InterpolatedSql#9]
Could be by design and that is fine, but in DapperQueryBuilder, I could do:

```
qb.AppendLine( fileKey != null
	? (FormattableString)$" AND f.UID = {fileKey}"
	: $" AND fo.Name = {folder:varchar(200)} AND f.Name = {fileName:varchar(200)}"
);
```

However, I get `Argument 1: cannot convert from 'System.FormattableString' to 'InterpolatedSql.IInterpolatedSql'` in InterpolatedSql.  I've found a few workarounds so maybe that is intention.  Let me know if method was missed or if I one of the workarounds below is the desired pattern going forward:

**Workaround 1 - no Ternary operator**
```
if ( fileKey != null )
{
	qb.AppendLine( $" AND f.UID = {fileKey}" );
}
else
{
	qb.AppendLine( $" AND fo.Name = {folder:varchar(200)} AND f.Name = {fileName:varchar(200)}" )
}
```

**Workaround 2 - Found this method I've never used before**
```
qb.AppendFormattableString( fileKey != null
	? (FormattableString)$" AND f.UID = {fileKey}"
	: $" AND fo.Name = {folder:varchar(200)} AND f.Name = {fileName:varchar(200)}"
);
```

**Workaround 3 - Appending via += seems to compile**
```
qb += fileKey != null
	? (FormattableString)$" AND f.UID = {fileKey}"
	: $" AND fo.Name = {folder:varchar(200)} AND f.Name = {fileName:varchar(200)}";
```

I'm going to test with number 3, but please advise.  Thanks.

**Comment by Drizin** [comment]
How did it go?

I think both 2 and 3 are good options.

Previously methods were just named "Append/AppendLine" (and would always take a FormattableString) but since I've introduced `InterpolatedStringHandlers` I had some issues with ambiguous overloads, and therefore in some places I had to use this explicitly-named `AppendFormattableString` (which does NOT add a leading linebreak, so you might want to start your strings with `\n`).

**Comment by Drizin** [comment]
@terryaney  Did it work? Can we close this?

**Comment by terryaney** [comment]
Pulled away, but actually was just working on finishing all my integration tests.  You can close this and I'll reopen if the issue presents itself?

**Comment by terryaney** [comment]
> @terryaney Did it work? Can we close this?

Yes it worked :)
